# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)(
      ^_assets/ |
      ^_db/ |
      ^_frontend/ |
      ^app/static/ |
      ^app/templates/ |
      ^clients/ |
      ^deploy/ |
      ^Houston.egg-info |
      ^virtualenv |
      ^migrations/versions/
  )
repos:
  # - repo: https://github.com/psf/black
  #   rev: stable
  #   hooks:
  #     - id: black
  #       language_version: python3.6
  - repo: local
    hooks:
      - id: brunette
        name: brunette
        description: Run Brunette on Python code (fork of Black).
        entry: brunette --config=setup.cfg
        language: system
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
